#!/bin/bash

# PSRJ            J2018+2839
# PSRB            B2016+28
# NAME            B2016+28
# RAJ             20:18:03.8333                 9.000e-04
# DECJ            +28:39:54.212                 1.600e-02
# DM              14.1977                       6.000e-04
# P0              0.5579534804225               7.000e-13
# P1              1.481058E-16                  1.600e-21
# S50             243                           1.210e+02
# S80             550                           2.700e+02
# S100            260
# S150            620
# S200            561                           4.100e+01
# S400            314                           3.000e+01
# S600            101                           1.300e+01
# S1400           30                            1.300e+01
# S5000           1.47                          2.800e-01
# W50             14.9
# W10             22.2

~/github/mwafrb/scripts/process_offline.sh J2018+2839 J2018+2839_Ch169.obsid 201803.8333 +283954.212  /datax2/mwa_fil/ 1 > J2018_ch169.out 2>&1
cd J2018+2839_Ch169/Fredda
/home/msok/github/mwafrb/scripts/prepare_all_plots.sh

