#!/bin/bash

do_plots=1
if [[ -n "$1" && "$1" != "-" ]]; then
   do_plots=$1
fi

# PSRJ            J1453-6413
# PSRB            B1449-64
# NAME            B1449-64
# RAJ             14:53:32.665                  6.000e-03
# DECJ            -64:13:16.00                  5.000e-02
# ELONG           243.44
# ELAT            -45.02
# DM              71.248                        2.000e-03
# W50             3.2
# W10             7.9

~/github/mwafrb/scripts/process_offline.sh J1453-6413 J1453-6413_Ch169.obsid 145332.665 -641316.00 /datax2/mwa_fil/ 1 - 1 480 0.001 169 > J1453_ch169.out 2>&1
cd J1453-6413_Ch169/Fredda

if [[ $do_plots -gt 0 ]]; then
   echo "/home/msok/github/mwafrb/scripts/prepare_all_plots.sh"
   /home/msok/github/mwafrb/scripts/prepare_all_plots.sh
else
   echo "WARNING : creating plots of FREDDA candidates is not required in order to execute manually, run command:"
   echo "          /home/msok/github/mwafrb/scripts/prepare_all_plots.sh"
fi




