#!/bin/bash

# PSRJ            J1752-2806
# PSRB            B1749-28
# NAME            B1749-28
# RAJ             17:52:58.6896                 1.700e-03
# DECJ            -28:06:37.3                   3.000e-01
~/github/mwafrb/scripts/process_offline.sh J1752-2806 J1752-2806_Ch145.obsid 175258.6896 -280637.3 /datax2/mwa_fil/ 1 > J1752_ch145.out 2>&1
# cd J0837+0610_Ch145/Folding
# ~/github/mwafrb/scripts/presto_fold_all.sh
# cd ../../
cd J1752-2806_Ch145/Fredda/
~/github/mwafrb/scripts/prepare_all_plots.sh


# ch=169 :
# cd ../../
# ~/github/mwafrb/scripts/process_offline.sh J0837+0610 J0837+0610_Ch169.obsid 083705.642 061014.56 /datax2/mwa_fil/ 1 > J0837_ch169.out 2>&1
# cd J0837+0610_Ch169/Fredda/
# ~/github/mwafrb/scripts/prepare_all_plots.sh


