#!/bin/bash

# PSRJ            J0534+2200
# PSRB            B0531+21
# NAME            B0531+21
# RAJ             05:34:31.973                  5.000e-03
# DECJ            +22:00:52.06                  6.000e-02
# ELONG           84.10
# ELAT            -1.29
# DM              56.77118                      2.400e-04
# P0              0.0333924123                  1.200e-09
# P1              4.20972E-13                   3.000e-18
# S150            7500                          3.800e+03
# S400            550                           1.000e+02
# S600            211                           3.700e+01
# S1400           14                            3.000e+00
# W50             3.0
# W10             4.7

do_plots=1
if [[ -n "$1" && "$1" != "-" ]]; then
   do_plots=$1
fi

~/github/mwafrb/scripts/process_offline.sh B0531+21 B0531+21_Ch121.obsid 053431.973 +220052.06 /datax2/mwa_fil/ 1 - - - 0.0001 > Crab_ch121.out 2>&1
cd B0531+21_Ch121/Fredda

if [[ $do_plots -gt 0 ]]; then
   echo "/home/msok/github/mwafrb/scripts/prepare_all_plots.sh"
   /home/msok/github/mwafrb/scripts/prepare_all_plots.sh
else
   echo "WARNING : creating plots of FREDDA candidates is not required in order to execute manually, run command:"
   echo "          /home/msok/github/mwafrb/scripts/prepare_all_plots.sh"
fi
