#!/bin/bash

# PSRJ            J0630-2834
# PSRB            B0628-28
# NAME            B0628-28
# ARAJ             06:30:49.404393               4.300e-05
# DECJ            -28:34:42.77881               3.700e-04
# ELONG           100.96
# ELAT            -51.73
# DM              34.425                        1.000e-03
# PEPOCH          46603.00
# F0              0.80358811986                 5.000e-11
# F1              -4.59962E-15                  1.300e-19
# P0              1.24441859615                 8.000e-11
# P1              7.1229E-15                    3.000e-19
# PMRA            -46.30                        9.900e-01
# PMDEC           21.26                         5.200e-01
# S50             1076                          5.380e+02
# S80             6590                          3.280e+03
# S150            640                           2.000e+01
# S200            271                           3.000e+00
# S400            206                           2.200e+01
# S600            106                           1.000e+01
# S800            90                            3.000e+01
# S1400           31.9                          6.400e+00
# W50             63
# W10             122
~/github/mwafrb/scripts/process_offline.sh J0630-2834 J0630-2834_Ch121.obsid 63049.404393 -283442.77881 /datax2/mwa_fil/ 1 > J0630_ch121.out 2>&1
cd J0630-2834_Ch121/Fredda
/home/msok/github/mwafrb/scripts/prepare_all_plots.sh

