#!/bin/bash

# /home/msok//github/mwafrb/scripts/prepare_csv.sh

~/github/mwafrb/scripts/process_offline.sh J0835-4510 Vela_Ch169.obsid 83520.61149 -451034.8751 /datax2/mwa_fil/ 1 > J0835_ch169.out 2>&1
cd Vela_Ch169/Fredda
/home/msok/github/mwafrb/scripts/prepare_all_plots.sh



