#!/bin/bash


min_snr=6
if [[ -n "$1" && "$1" != "-" ]]; then
   min_snr=$1
fi

max_snr=1000000000
if [[ -n "$2" && "$2" != "-" ]]; then
   max_snr=$2
fi

do_open=1
if [[ -n "$3" && "$3" != "-" ]]; then
   do_open=$3
fi

infile=merged_fredda.cand
if [[ -n "$4" && "$4" != "-" ]]; then
   infile=$4
fi

fits=i_00000.fits
if [[ -n "$5" && "$5" != "-" ]]; then
   fits=$5
fi


for merged_cand_file in `ls *.cand_merged`
do
   fits_file=${merged_cand_file%%norm.cand_merged}out_t.fits

   echo "ds9_fredda_all! $min_snr $max_snr $do_open $merged_cand_file $fits_file"
   sleep 1
   ds9_fredda_all! $min_snr $max_snr $do_open $merged_cand_file $fits_file
done
